GRANT CONNECT ON DATABASE restaurant_reviews_test_db TO "APICONNECTION808";
GRANT USAGE ON SCHEMA public TO "APICONNECTION808";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "APICONNECTION808";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "APICONNECTION808";
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO "APICONNECTION808";